server:
  port: 8761
  
spring:
  application:
    name: service-registry
    
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false    # this app itself should not register itself as service
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
    
    

