server:
  port: 8081
  
eureka:
  client:
      serviceUrl:
       defaultZone: http://localhost:8761/eureka/
   
#for publishing 100%  matrices data to zipkin    
management:
 tracing:
  sampling:
   probability: 1.0